// <auto-generated />
using Footty.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace footty.Migrations
{
    [DbContext(typeof(FoottyContext))]
    [Migration("20230531122712_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("footty.Models.Match", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("date")
                        .HasColumnType("TEXT");

                    b.Property<int>("opponent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("opponent_goals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("place")
                        .HasColumnType("TEXT");

                    b.Property<int>("team")
                        .HasColumnType("INTEGER");

                    b.Property<int>("team_goals")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("footty.Models.Player", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("assists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("games_played")
                        .HasColumnType("INTEGER");

                    b.Property<int>("goals_scored")
                        .HasColumnType("INTEGER");

                    b.Property<float>("minutes_played")
                        .HasColumnType("REAL");

                    b.Property<string>("position")
                        .HasColumnType("TEXT");

                    b.Property<string>("shirt_number")
                        .HasColumnType("TEXT");

                    b.Property<int>("team")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("footty.Models.Stadium", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("city")
                        .HasColumnType("TEXT");

                    b.Property<float>("latitude")
                        .HasColumnType("REAL");

                    b.Property<float>("longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("team")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Stadium");
                });

            modelBuilder.Entity("footty.Models.Team", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
